//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal labels() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de vous authentifier..
        /// </summary>
        internal static string AnonymeText {
            get {
                return ResourceManager.GetString("AnonymeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , vous êtes authentifié comme administrateur..
        /// </summary>
        internal static string AuthentifieAdmin {
            get {
                return ResourceManager.GetString("AuthentifieAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , vous êtes authentifié comme un ami..
        /// </summary>
        internal static string AuthentifieAmi {
            get {
                return ResourceManager.GetString("AuthentifieAmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , vous êtes authentifié comme éditeur..
        /// </summary>
        internal static string AuthentifieEditeur {
            get {
                return ResourceManager.GetString("AuthentifieEditeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vous êtes authentifié..
        /// </summary>
        internal static string AuthentifieText {
            get {
                return ResourceManager.GetString("AuthentifieText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour .
        /// </summary>
        internal static string BonjourText {
            get {
                return ResourceManager.GetString("BonjourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string ChangePasswordButtonText {
            get {
                return ResourceManager.GetString("ChangePasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer :.
        /// </summary>
        internal static string ChangePasswordConfirmNewPasswordLabelText {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmNewPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un utilisateur.
        /// </summary>
        internal static string ChangePasswordCreateUserText {
            get {
                return ResourceManager.GetString("ChangePasswordCreateUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editez votre Profil.
        /// </summary>
        internal static string ChangePasswordEditProfileText {
            get {
                return ResourceManager.GetString("ChangePasswordEditProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez votre Nom d&apos;utilisateur et votre ancien Mot de passe..
        /// </summary>
        internal static string ChangePasswordInstructionText {
            get {
                return ResourceManager.GetString("ChangePasswordInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier votre mot de passe :.
        /// </summary>
        internal static string ChangePasswordTitre {
            get {
                return ResourceManager.GetString("ChangePasswordTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le rôle ***role*** Existe déjà..
        /// </summary>
        internal static string CreateNewRoleErreurRoleExist {
            get {
                return ResourceManager.GetString("CreateNewRoleErreurRoleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Donner un rôle à créer..
        /// </summary>
        internal static string CreateNewRoleErreurRoleSelected {
            get {
                return ResourceManager.GetString("CreateNewRoleErreurRoleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le rôle ***role*** à été créé avec succès..
        /// </summary>
        internal static string CreateNewRoleSuccess {
            get {
                return ResourceManager.GetString("CreateNewRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Rôle ***role*** &lt;u&gt;n&apos;as pas été&lt;/u&gt; créé..
        /// </summary>
        internal static string CreateNewRoleSuccessErreurCreated {
            get {
                return ResourceManager.GetString("CreateNewRoleSuccessErreurCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un rôle à ajouter..
        /// </summary>
        internal static string CreateRoleAddRoleErreurRoleSelected {
            get {
                return ResourceManager.GetString("CreateRoleAddRoleErreurRoleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur ***user*** existe déjà dans le rôle ***role***..
        /// </summary>
        internal static string CreateRoleAddRoleErreurUseInRolerExist {
            get {
                return ResourceManager.GetString("CreateRoleAddRoleErreurUseInRolerExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un utilisateur..
        /// </summary>
        internal static string CreateRoleAddRoleErreurUserSelected {
            get {
                return ResourceManager.GetString("CreateRoleAddRoleErreurUserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rôle ***role*** ajouter avec succès à l&apos;utilisateur ***user***..
        /// </summary>
        internal static string CreateRoleAddRoleUserInRoleSuccess {
            get {
                return ResourceManager.GetString("CreateRoleAddRoleUserInRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rôles Application :.
        /// </summary>
        internal static string CreateRoleApplication {
            get {
                return ResourceManager.GetString("CreateRoleApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string CreateRoleBoutonAnnuler {
            get {
                return ResourceManager.GetString("CreateRoleBoutonAnnuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer.
        /// </summary>
        internal static string CreateRoleBoutonEditer {
            get {
                return ResourceManager.GetString("CreateRoleBoutonEditer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer un utilisateur.
        /// </summary>
        internal static string CreateRoleBoutonEditerToolTip {
            get {
                return ResourceManager.GetString("CreateRoleBoutonEditerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string CreateRoleBoutonSupprimer {
            get {
                return ResourceManager.GetString("CreateRoleBoutonSupprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string CreateRoleBoutonSupprimerRole {
            get {
                return ResourceManager.GetString("CreateRoleBoutonSupprimerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un rôle.
        /// </summary>
        internal static string CreateRoleBoutonSupprimerRoleToolTip {
            get {
                return ResourceManager.GetString("CreateRoleBoutonSupprimerRoleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un utilisateur.
        /// </summary>
        internal static string CreateRoleBoutonSupprimerToolTip {
            get {
                return ResourceManager.GetString("CreateRoleBoutonSupprimerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer le rôle.
        /// </summary>
        internal static string CreateRoleButton {
            get {
                return ResourceManager.GetString("CreateRoleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un utilisateur.
        /// </summary>
        internal static string CreateRoleHyperLinkCreerUtilisateur {
            get {
                return ResourceManager.GetString("CreateRoleHyperLinkCreerUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la page sécurisée.
        /// </summary>
        internal static string CreateRoleHyperLinkPageSecurisee {
            get {
                return ResourceManager.GetString("CreateRoleHyperLinkPageSecurisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateurs du rôle  :.
        /// </summary>
        internal static string CreateRoleLabelRoleApplication {
            get {
                return ResourceManager.GetString("CreateRoleLabelRoleApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un rôle :.
        /// </summary>
        internal static string CreateRoleLableCreerRole {
            get {
                return ResourceManager.GetString("CreateRoleLableCreerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes le dernier &quot;Administrateur&quot; de cette application.
        ///Vous ne pouvez pas vous supprimer de ce rôle..
        /// </summary>
        internal static string CreateRoleRemoveRoleErreurLastAdmin {
            get {
                return ResourceManager.GetString("CreateRoleRemoveRoleErreurLastAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un rôle à supprimer de l&apos;utilisateur..
        /// </summary>
        internal static string CreateRoleRemoveRoleErreurUserInRoleSelected {
            get {
                return ResourceManager.GetString("CreateRoleRemoveRoleErreurUserInRoleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un utilisateur à supprimer dans ce rôle..
        /// </summary>
        internal static string CreateRoleRemoveRoleErreurUserSelected {
            get {
                return ResourceManager.GetString("CreateRoleRemoveRoleErreurUserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rôle ***role*** retiré avec succès de l&apos;utilisateur ***user***..
        /// </summary>
        internal static string CreateRoleRemoveRoleSuccess {
            get {
                return ResourceManager.GetString("CreateRoleRemoveRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rôles Utilisateur :.
        /// </summary>
        internal static string CreateRoleRoleUtilisateur {
            get {
                return ResourceManager.GetString("CreateRoleRoleUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérer les utilisateurs avec :.
        /// </summary>
        internal static string CreateRoleTitre {
            get {
                return ResourceManager.GetString("CreateRoleTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les Utilisateurs  :.
        /// </summary>
        internal static string CreateRoleUtilisateur {
            get {
                return ResourceManager.GetString("CreateRoleUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer un nouvel utilisateur.
        /// </summary>
        internal static string CreateUserText {
            get {
                return ResourceManager.GetString("CreateUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un utilisateur à éditer..
        /// </summary>
        internal static string EditerUtilisateurErreurUserSelected {
            get {
                return ResourceManager.GetString("EditerUtilisateurErreurUserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse de messagerie :.
        /// </summary>
        internal static string EditProfileAdresseMessagerie {
            get {
                return ResourceManager.GetString("EditProfileAdresseMessagerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string EditProfileBoutonModifier {
            get {
                return ResourceManager.GetString("EditProfileBoutonModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string EditProfileBoutonSupprimer {
            get {
                return ResourceManager.GetString("EditProfileBoutonSupprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm password :.
        /// </summary>
        internal static string EditProfileConfirmPassWord {
            get {
                return ResourceManager.GetString("EditProfileConfirmPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de création :.
        /// </summary>
        internal static string EditProfileDateCreation {
            get {
                return ResourceManager.GetString("EditProfileDateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernière activité sur le site :.
        /// </summary>
        internal static string EditProfileDerniereActivite {
            get {
                return ResourceManager.GetString("EditProfileDerniereActivite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernière connexion :.
        /// </summary>
        internal static string EditProfileDerniereConnexion {
            get {
                return ResourceManager.GetString("EditProfileDerniereConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernier mot de passe changé le  :.
        /// </summary>
        internal static string EditProfileDerniereMotDePass {
            get {
                return ResourceManager.GetString("EditProfileDerniereMotDePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe :.
        /// </summary>
        internal static string EditProfilePassWord {
            get {
                return ResourceManager.GetString("EditProfilePassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question de sécurité :.
        /// </summary>
        internal static string EditProfileQuestionSecurite {
            get {
                return ResourceManager.GetString("EditProfileQuestionSecurite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réponse de sécurité :.
        /// </summary>
        internal static string EditProfileReponseSecurite {
            get {
                return ResourceManager.GetString("EditProfileReponseSecurite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer/Modifier votre profil.
        /// </summary>
        internal static string EditProfileTitre {
            get {
                return ResourceManager.GetString("EditProfileTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur :.
        /// </summary>
        internal static string EditProfileUserName {
            get {
                return ResourceManager.GetString("EditProfileUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur à l&apos;envoit de la Confirmation :.
        /// </summary>
        internal static string ErreurEnvoitConfirmation {
            get {
                return ResourceManager.GetString("ErreurEnvoitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de l&apos;adresse de messagerie n&apos;est pas valide..
        /// </summary>
        internal static string FormatAdresseNonValide {
            get {
                return ResourceManager.GetString("FormatAdresseNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide ?.
        /// </summary>
        internal static string HelpPageText {
            get {
                return ResourceManager.GetString("HelpPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide ?.
        /// </summary>
        internal static string HyperLinkAide {
            get {
                return ResourceManager.GetString("HyperLinkAide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer votre mot de passe.
        /// </summary>
        internal static string HyperLinkChangePasswordText {
            get {
                return ResourceManager.GetString("HyperLinkChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérer les rôles utilisateurs.
        /// </summary>
        internal static string HyperLinkCreateRoleText {
            get {
                return ResourceManager.GetString("HyperLinkCreateRoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editez votre profil utilisateur.
        /// </summary>
        internal static string HyperLinkEditProfileText {
            get {
                return ResourceManager.GetString("HyperLinkEditProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrez un nouvel utilisateur.
        /// </summary>
        internal static string HyperLinkEnregistrezUtilisateur {
            get {
                return ResourceManager.GetString("HyperLinkEnregistrezUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accédez à l&apos;application sécurisée.
        /// </summary>
        internal static string HyperLinkPageSecurisee {
            get {
                return ResourceManager.GetString("HyperLinkPageSecurisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connectez-vous.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connectez-vous à l&apos;application.
        /// </summary>
        internal static string LoginTitleText {
            get {
                return ResourceManager.GetString("LoginTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnectez-vous.
        /// </summary>
        internal static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réponse :.
        /// </summary>
        internal static string PasswordRecoveryAnswer {
            get {
                return ResourceManager.GetString("PasswordRecoveryAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe est : ***pass***.
        /// </summary>
        internal static string PasswordRecoveryEmailBody {
            get {
                return ResourceManager.GetString("PasswordRecoveryEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sujet : votre mot de passe dans le module login.
        /// </summary>
        internal static string PasswordRecoveryEmailSubject {
            get {
                return ResourceManager.GetString("PasswordRecoveryEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la récupération de votre mot de passe :.
        /// </summary>
        internal static string PasswordRecoveryFailed {
            get {
                return ResourceManager.GetString("PasswordRecoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez un nom d&apos;utilisateur..
        /// </summary>
        internal static string PasswordRecoveryPageLoadMessage {
            get {
                return ResourceManager.GetString("PasswordRecoveryPageLoadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question de mot de passe :.
        /// </summary>
        internal static string PasswordRecoveryQuestion {
            get {
                return ResourceManager.GetString("PasswordRecoveryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répondez à la question de mot de passe..
        /// </summary>
        internal static string PasswordRecoveryQuestionEmpty {
            get {
                return ResourceManager.GetString("PasswordRecoveryQuestionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyez mon mot de passe.
        /// </summary>
        internal static string PasswordRecoverySendPassWordMassage {
            get {
                return ResourceManager.GetString("PasswordRecoverySendPassWordMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe vous à été envoyé par email..
        /// </summary>
        internal static string PasswordRecoverySuccess {
            get {
                return ResourceManager.GetString("PasswordRecoverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe oublié ?.
        /// </summary>
        internal static string PasswordRecoveryText {
            get {
                return ResourceManager.GetString("PasswordRecoveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrouvez votre mot de passe, répondez à la question :.
        /// </summary>
        internal static string PasswordRecoveryTitre {
            get {
                return ResourceManager.GetString("PasswordRecoveryTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;Utilisateur :.
        /// </summary>
        internal static string PasswordRecoveryUserName {
            get {
                return ResourceManager.GetString("PasswordRecoveryUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur ***user*** n&apos;existe pas. Vérifiez votre nom d&apos;utilisateur..
        /// </summary>
        internal static string PasswordRecoveryUserNotFound {
            get {
                return ResourceManager.GetString("PasswordRecoveryUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mémoriser ma connexion.
        /// </summary>
        internal static string RememberMeText {
            get {
                return ResourceManager.GetString("RememberMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        internal static string SiteMapNodeAccueil {
            get {
                return ResourceManager.GetString("SiteMapNodeAccueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes le dernier &quot;Administrateur&quot; de cette application.
        ///Vous ne pouvez pas vous supprimer.\n.
        /// </summary>
        internal static string SupprimeProfileButtonSupprimerLastAdmin {
            get {
                return ResourceManager.GetString("SupprimeProfileButtonSupprimerLastAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre compte a été supprimé..
        /// </summary>
        internal static string SupprimeProfileButtonSupprimerUserDeletedSuccess {
            get {
                return ResourceManager.GetString("SupprimeProfileButtonSupprimerUserDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer votre compte ?.
        /// </summary>
        internal static string SupprimeProfileTitre {
            get {
                return ResourceManager.GetString("SupprimeProfileTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse de messagerie :.
        /// </summary>
        internal static string SupprimeProfileUserEmail {
            get {
                return ResourceManager.GetString("SupprimeProfileUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;Utilisateur :.
        /// </summary>
        internal static string SupprimeProfileUserName {
            get {
                return ResourceManager.GetString("SupprimeProfileUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez pas supprimer le role &quot;Administrateur&quot;..
        /// </summary>
        internal static string SupprimerRoleErreurRoleAdminSelected {
            get {
                return ResourceManager.GetString("SupprimerRoleErreurRoleAdminSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un rôle à supprimer..
        /// </summary>
        internal static string SupprimerRoleErreurRoleSelected {
            get {
                return ResourceManager.GetString("SupprimerRoleErreurRoleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Rôle ***role*** n&apos;as pas pu être supprimé..
        /// </summary>
        internal static string SupprimerRoleFailed {
            get {
                return ResourceManager.GetString("SupprimerRoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le rôle ***role*** supprimé avec succès..
        /// </summary>
        internal static string SupprimerRoleSuccess {
            get {
                return ResourceManager.GetString("SupprimerRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ***user*** est le dernier &quot;Administrateur&quot; de cette application. Vous ne pouvez pas le supprimer..
        /// </summary>
        internal static string SupprimerUtilisateurErreurLastAdmin {
            get {
                return ResourceManager.GetString("SupprimerUtilisateurErreurLastAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes en train de supprimer votre compte.
        ///Pour cela vous devez passez pas le formulaire de suppression d&apos;un compte..
        /// </summary>
        internal static string SupprimerUtilisateurErreurUserDeletedHimself {
            get {
                return ResourceManager.GetString("SupprimerUtilisateurErreurUserDeletedHimself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un utilisateur à supprimer..
        /// </summary>
        internal static string SupprimerUtilisateurErreurUserSelected {
            get {
                return ResourceManager.GetString("SupprimerUtilisateurErreurUserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur ***user*** a été supprimé avec succès..
        /// </summary>
        internal static string SupprimerUtilisateurSuccess {
            get {
                return ResourceManager.GetString("SupprimerUtilisateurSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page d&apos;acceuil - Status de connexion -.
        /// </summary>
        internal static string TitrePage {
            get {
                return ResourceManager.GetString("TitrePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sodevlog - Module d&apos;authentification.
        /// </summary>
        internal static string TitreSite {
            get {
                return ResourceManager.GetString("TitreSite", resourceCulture);
            }
        }
    }
}
